### ISSUE TITLE
Issue on page /concert.html

### ISSUE THREAD

**Issue by telephon** [capital-G/xenakis-workgroup#4]
"When a molecule rotates alone in space, it do not continue to do so forever."
should be
"When a molecule rotates alone in space, it does not continue to do so forever."

**Comment by capital-G** [comment]
I think there were also some additional changes you requested - do you want to make a PR? The file is https://github.com/capital-G/xenakis-workgroup/blob/main/concert.md , after a merge to main it gets automatically build as a website and deployed.

edit: in case you wonder - its a custom md dialect (but a really nice one): https://jupyterbook.org/reference/cheatsheet.html

**Comment by telephon** [comment]
ah cool, I'll try. I had just found the issue button right now.
